name: Coverage
on:
    pull_request:
        branches:
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout Repository
              uses: actions/checkout@v4

            # Install NodeJS
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: "22.16.0"

            # Install pnpm
            - uses: pnpm/action-setup@v4

            # Install dependencies and bundle the software
            - name: Initialize
              run: |
                  git config --global user.name "Tester"
                  git config --global user.email "tester@weichwarenprojekt.de"
                  pnpm i
                  pnpm run build

            - name: Test
              run: pnpm exec vitest --coverage
            - name: Report Coverage
              uses: davelosert/vitest-coverage-report-action@v1
