name: Coverage
on:
    pull_request:
        branches:
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            # Install NodeJS
            - name: Install NodeJS
              uses: actions/setup-node@v1
              with:
                  node-version: "18.13.0"

            # Run the coverage reporter
            - uses: actions/checkout@v3

            # Install dependencies and bundle the software
            - name: Initialize
              run: |
                  npm i
                  npm run build

            - uses: ArtiomTr/jest-coverage-report-action@v2
