name: Coverage
on:
    pull_request:
        branches:
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            # Install NodeJS
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: "22.8.0"

            # Run the coverage reporter
            - uses: actions/checkout@v3

            # Install dependencies and bundle the software
            - name: Initialize
              run: |
                  git config --global user.name "Tester"
                  git config --global user.email "tester@weichwarenprojekt.de"
                  npm i
                  npm run build

            - name: Test
              run: npx vitest --coverage
            - name: Report Coverage
              uses: davelosert/vitest-coverage-report-action@v1
